name: Build and Publish Docker Image

on:
  push:
    branches:
      - master  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Build Docker image
        run: |
          docker build -t docker.pkg.github.com/${{ github.repository }}/t2-spa:latest .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: |
          docker push docker.pkg.github.com/${{ github.repository }}/t2-spa:latest
