name: Build and Publish Docker Image

on:
  push:
    branches:
      - master  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t docker.pkg.github.com/${{ github.repository }}/t2-spa:latest .

      - name: Push Docker image
        run: |
          docker push docker.pkg.github.com/${{ github.repository }}/t2-spa:latest
