name: Build and Publish Docker Image

on:
  push:
    branches:
      - master  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/gabrielcruzsoto/t2-spa:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/gabrielcruzsoto/t2-spa:latest
